service:
  port: 3000
  name: st-app
session:
  secret: game
database:
  user:
    connection: <{MONGO_CONNECTION}>/users
    collection: users
  account:
    connection: <{MONGO_CONNECTION}>/accounts
    collection: accounts
  servers:
    connection: <{MONGO_CONNECTION}>/servers
    collection: servers
  items: 
    connection: <{MONGO_CONNECTION}>/items
    collection: items
  guild:
    connection: <{MONGO_CONNECTION}>/guilds
    collection: guilds
game:
  version: 29