export class User {
    user_id;
    location_type;
    room_number;
    game_id;
    rank;
    gp;
    gold;
    cash;
    gender;
    unlock;
    head;
    body;
    eyes;
    flag;
    background;
    foreground;
    event1;
    event2;
    photo_url;
    guild;
    guild_job;
    name_changes;
    power_user;
    tournament;
    plus10gp;
    mobile_fox;
    country;
    relationship_status;
    relationship_with_id;
    relationship_with_rank;
    relationship_with_photo;
    relationship_with_name;
    relationship_with_gender;
    maps_pack;
    prix_points;
    megaphones;
    lucky_egg_sec_left;
    prix_points_type;
    prix_points_reset_price;

    constructor() {}
}