module.exports = {
    NOCHANGE     : -1,
    THOR          : 0,
    WIND_CHANGE   : 1,
    NOITEMS       : 2,
    SUN           : 3,
    LIGHTNING     : 4,
    BLACK         : 5,
    RANDOM        : 6,
    MIRROR        : 7,
    TORNADO       : 8,
    NONE          : 9,
    MOON          : 10,
    LAND          : 11,
}